INPUT_REVIEW=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/dataset/hotel-review.csv
INPUT_STOP=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/dataset/stopwords.txt
OUT_TASK1=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_1_out
OUT_TASK2A=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_2a_out
OUT_TASK2B=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_2b_out
OUT_TASK2C=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_2c_out
OUT_TASK3A=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_3a_out
OUT_TASK3B=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_3b_out
OUT_TASK4A=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_4a_out
OUT_TASK4B=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_4b_out
OUT_TASK5=/d/code_nam_3/big_data/thuc_hanh_lab2/ThanhAn/output/task_5_out
